title: Cynthia's Blog
author: Cynthia Shankar
email: cynthia_shankar9@gmail.com
description: > Hi! My name is Cynthia **The test will be bold**
I am a grade 9 experiencing my first year of highschool at A.Y Jackson Secondary school. I enjoy learning about math and science during school, and I endure myself in plenty of hobbies that always keep me busy.On my blog I discuss and write about my hobbies, my everyday life and interesting things that I feel are worth sharing!


# social links
twitter_username: @cynthia109
github_username:  @Cynthia09

show_excerpts: true 

theme: minima
